# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a0e02aed330f5733bd6201fb7b39a6e7281339b1d16195fab11128881ed3c8e6b167238e9cdccc9b034a97c7f399ecd6b3c5413fd6ba49048e01e7f902dbd09

test:
  secret_key_base: 8e400f74fe4d28de7e1db75354a8ee28a10f8255e72d85394f047809f06479f02958a3a5cb243d9e3e6777ac2158e819285596bbc520968880f4617e6eafb3cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
